---  
- hosts: localhost
  connection: local
  gather_facts: no    
  roles:
    - client

- name: another play
  hosts: localhost
  tasks:
    - debug: msg=hello

- name: Start Client
  gather_facts: no
  user: ubuntu
  hosts: ec2_client
  become: yes
  roles:
    - startClient

