---
- name: get ServerIP from localhost
  set_fact: endpoint="{{ hostvars[ 'localhost' ].privateip }}"

- name: Update Server IP on client
  replace:
     dest: /home/ubuntu/final_tests/tests/workload
     regexp: 'url.prefix=.+'
     replace: 'url.prefix={{ endpoint }}/'
     #replace: 'url.prefix="hello/";'

- name: Update Server IP on client
  replace:
     dest: /home/ubuntu/initial_tests/tests/workload
     regexp: 'url.prefix=.+'
     replace: 'url.prefix={{ endpoint }}/'
     #replace: 'url.prefix="hello/";'

- name: Update execution time for Test Run
  replace:
     dest: /home/ubuntu/initial_tests/tests/workload
     regexp: 'maxexecutiontime=.+'
     replace: 'maxexecutiontime=10'

- name: Run initial Setup
  shell: /home/ubuntu/initial_tests/tests/test

- name: Update execution time for exeriment Run
  replace:
     dest: /home/ubuntu/final_tests/tests/workload
     regexp: 'maxexecutiontime=.+'
     replace: 'maxexecutiontime={{ max_execution_time }}'

- name: Update maximum operations per second
  replace:
     dest: /home/ubuntu/final_tests/tests/test
     regexp: 'LIMIT=.+'
     replace: 'LIMIT={{ max_ops }}'
  

- name: Run Experiments
  shell: /home/ubuntu/final_tests/tests/test
