---
- name: get ServerIP from localhost
  set_fact: endpoint="{{ hostvars[ 'localhost' ].privateip }}"
#  set_fact: endpoint="199.99.99.102"

- name: Update Server IP on client
  replace:
     dest: /home/ubuntu/final_tests/tests/workload
     regexp: 'url.prefix=.+'
     replace: 'url.prefix={{ endpoint }}/'
     #replace: 'url.prefix="hello/";'

- name: Update execution time for exeriment Run
  replace:
     dest: /home/ubuntu/final_tests/tests/workload
     regexp: 'maxexecutiontime=.+'
     replace: 'maxexecutiontime={{ max_execution_time }}'

- name: Update maximum operations per second
  replace:
     dest: /home/ubuntu/final_tests/tests/test
     regexp: 'LIMIT=.+'
     replace: 'LIMIT={{ max_ops }}'
  
- name: Update Server IP on setup script
  replace:
     dest: /home/ubuntu/findreponsetime/responsetime.sh
     regexp: '172.31.47.97'
     replace: '{{ endpoint }}'


