---  
- name: create key pair  
  tags: keypair  
  ec2_key:  
    region: "{{ region }}"  
    name: "{{ keyname }}"      
  register: mykey  

- name: write the private key to file
  copy: content="{{ mykey.key.private_key }}" dest="~/.ssh/{{ keyname }}.pem" mode=0600
  when: mykey.changed

- name: create security group  
  tags: sg
  ec2_group:    
    region: "{{ region }}"
    #your security group name  
    name: sg_archival    
    description: security group for all virtual machines
    rules:
      # allow ssh access from your ip address  
      - proto: tcp  
        from_port: 22  
        to_port: 22  
        cidr_ip: "{{ allowed_ip }}"  
      # allow http access from anywhere  
      - proto: tcp  
        from_port: 80    
        to_port: 80    
        cidr_ip: 0.0.0.0/0    
      # allow https access from anywhere  
      - proto: tcp  
        from_port: 443    
        to_port: 443    
        cidr_ip: 0.0.0.0/0
      - proto: tcp  
        from_port: 3306    
        to_port: 3306    
        cidr_ip: 0.0.0.0/0
    rules_egress:  
      - proto: all  
        cidr_ip: 0.0.0.0/0    
