---  
- name: launch ec2 instance  
  tags: ec2
  local_action:  
    module: ec2  
    region: "{{ region }}"  
    zone: "{{ zone }}"
    key_name: "{{ keyname }}"
    monitoring: yes
    instance_type: "{{ instance_type }}"    
    image: "{{ image }}"  
    wait: yes    
    group: sg_archival  
    instance_tags:  
      Name: server-{{ max_page_cache }}  
      class: server
  register: ec2

- name: Find IP
  set_fact: privateip="{{ ec2['instances'][0]['private_ip'] }}"

- name: Debug
  debug:
    msg: "{{ privateip }}"

- name: Add to host list
  add_host:
    name: "{{ ec2.instances[0].public_ip }}"
    group: ec2_server

- name: Debug
  debug:
    msg: ":{{ ec2.instances[0].public_ip }}:"

